### ISSUE TITLE
How do I implement a SSL Certificate Chain File for Bitnami's Apache2 running in a docker container

### ISSUE THREAD

**Issue by nolssmit** [bitnami/bitnami-docker-apache#105]
Hi,

I'm using a subdomain from [No-IP](https://my.noip.com) and bought their proposed SSL certificate from [TrustCor](https://trustcor.com) and installed it by:

- Mapping the certs folder of Apache running in a docker container (see my docker-compose.yml file below) to my persistent apache-certs folder
- Following the steps in Binami's Apache documentation:  [Using custom SSL certificates](https://github.com/bitnami/bitnami-docker-apache)
- Renamed my downloaded PEM Chain file (slimzulu.hopto.org.pem-chain) to server-ca.crt, PEM file (slimzulu.hopto.org.pem) to server.crt and my slimzulu.hopto.org.key to server.key and copied them to my persistent apache-certs folder

I then followed the steps explained by [TrustCor](https://trustcor.com/support/ssl-install/apache-ssl-installation.php) to modify the virtual host file to implement the SSL Certificate Chain File (see my my-vhost.conf file below).

but if I use the service from [SSLShopper](https://www.sslshopper.com/ssl-checker.html#hostname=slimzulu.hopto.org) to verify the implementation, I get the following response:

> The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error. The fastest way to fix this problem is to contact your SSL provider.

**The relevant part of my docker-compose.yml file**
```
  apache:
    restart: unless-stopped
    container_name: apache
    image: bitnami/apache:latest
    environment:
      - APACHE_HTTP_PORT_NUMBER=8080 
      - APACHE_HTTPS_PORT_NUMBER=8443
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./apache_data:/app
      - ./apache-certs:/certs
      - .my_vhost.conf:/vhosts/my_vhost.conf:ro
```

**My my_vhost.conf file**
```
<VirtualHost *:8080>
  ServerName slimzulu.hopto.org
  SSLCertificateChainFile ./apache-certs/server-ca.crt

  DocumentRoot "/app"
  <Directory "/app">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
```

Bitnami's Apache documentation is not clear how to implement a SSL Certificate Chain File for Apache running in a docker container.

Help will be highly appreciated to resolve this issue.

Regards,

Nols Smit
