### ISSUE TITLE
Apache2 custom entrypoint

### ISSUE THREAD

**Issue by Maximilian-Schwarz** [bitnami/bitnami-docker-apache#109]
Hello,

I'm using the bitnami/apache:latest and the bitnami/php-fpm:7.4.26-prod docker image.
I extend the apache docker file in a separate file, where I define a entrypoint to download Shopware and create the volumes. If I start with docker-compose up I always got the following error:

`apache2 exited with code 1`

docker-compose.yml:
```yaml
version: "3"
services:
  apache:
    container_name: apache2
    build: './config/apache2/'
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - php
    volumes:
      - ./src:/app/.htaccess
      - ./src/custom:/app/custom
      - ./src/themes:/app/themes
      - ./src/plugins:/app/engine/Shopware/Plugins
      - files:/app/files
      - media:/app/media
      - log:/app/var/log

  php:
    container_name: php
    build: './config/php/'
    ports:
      - 9000:9000
    volumes:
      - ./src:/app
      - ./config/php/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini

volumes:
  files:
  media:
  log:
```

config/apache2/Dockerfile:
```Dockerfile
FROM bitnami/apache:latest

# Change user to perform privileged actions
USER 0

# Install apache2
RUN apt update && apt-get dist-upgrade -y && apt install -y \
    wget \
    zip

# Create volumes
VOLUME ["/app/files", "/app/media", "/app/var/log"]

# Set workdir
WORKDIR /app

COPY ./docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["sh", "/docker-entrypoint.sh"]
```

config/apache2/docker-entrypoint.sh:
```bash
#!/usr/bin/env bash
set -e

if [ ! -f ./app/install.lock ]
then
	echo "##### Download shopware #####"
	wget "https://www.shopware.com/de/Download/redirect/version/sw5/file/install_5.7.6_32510831fc10df11821cf6de6aa03de47fd40255.zip" -O /app/shopware.zip
	unzip /app/shopware.zip && rm /app/shopware.zip
fi
```

What did I wrong? Any help? Without the custom entry point the ddoc
