### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by svycka** [bitnami/bitnami-docker-apache#21]
config:
```yml
apache:
    image: bitnami/apache
    ports:
        - 80:80
    volumes:
        - .:/app
        - ./vhosts:/bitnami/apache/conf/vhosts
        - ./logs:/bitnami/apache/logs
```
response:
> Forbidden
>
> You don't have permission to access / on this server.
> Server unable to read htaccess file, denying access to be safe

how can I fix this?
