### ISSUE TITLE
map local to apache /app folder

### ISSUE THREAD

**Issue by robbygallo** [bitnami/bitnami-docker-apache#79]
I have tried to map local folder to /app with insuccess

I have tried with relative and absolute path

```
version: '2'

services:
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../:/app
      - ./apache_data/vhost:/bitnami/apache/conf/vhost 
      - ./apache_data/logs:/bitnami/apache/logs
```

The vhost map is working, but ../:/app is not working.

Can you help me, please
