### ISSUE TITLE
About file sync failure

### ISSUE THREAD

**Issue by mozgbrasil** [bitnami/bitnami-docker-apache#85]
Good afternoon

-

About file sync failure

-

**Description**

According to images

[low_resolution_2018-05-16_10-33-08.pdf](https://github.com/bitnami/bitnami-docker-apache/files/2009320/low_resolution_2018-05-16_10-33-08.pdf)

As you can see, when updating the file, this change is not being displayed in the webserver of the container

It takes a few minutes to display the file change

**Steps to reproduce the issue:**

Based on

https://docs.bitnami.com/containers/how-to/create-amp-environment-containers/

docker-compose.yml

```
  version: '2'

  services:
    apache:
      image: bitnami/apache:latest
      ports:
        - 80:80
      volumes:
        # ---- Format: ----
        # HOST-DIRECTORY : DOCKER-DIRECTORY
        # Mount volumes related to ln -s htdocs
        - /home/marcio/dados:/home/marcio/dados
        # Mount custom mass virtual hosting
        - ~/dados/mount/www:/app
        # Mount custom apache-vhost
        - ~/dados/mount/apache-vhost:/bitnami/apache/conf/vhosts

    php-fpm:
      image: bitnami/php-fpm:latest
      volumes:
        # Mount custom mass virtual hosting
        - ~/dados/mount/www:/app

    fix-mariadb-permissions:
      image: 'bitnami/mariadb:latest'
      user: root
      command: chown -R 1001:1001 /bitnami
      volumes:
        - ~/dados/mount/mariadb-data:/bitnami
    mariadb:
      image: 'bitnami/mariadb:latest'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      ports:
        - '3306'
      volumes:
        - ~/dados/mount/mariadb-data:/bitnami
      depends_on:
        - fix-mariadb-permissions
    phpmyadmin:
      image: bitnami/phpmyadmin:latest
      depends_on:
        - mariadb
      ports:
        - '88:80'
      volumes:
        - ~/dados/mount/mariadb-data:/bitnami
```

**Describe the results you received:**

slow sync

**Describe the results you expected:**

immediate synchrony

**Additional information you deem important (e.g. issue happens only occasionally):**

ever

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.06.0-ce-dev
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f7c75f3
 Built:        Tue May 15 14:57:43 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.06.0-ce-dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f7c75f3
  Built:        Tue May 15 14:55:54 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

- Output of `docker info`:

```
Containers: 55
 Running: 1
 Paused: 0
 Stopped: 54
Images: 3
Server Version: 18.06.0-ce-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.668GiB
Name: marcio-Inspiron-7520
ID: AXXH:MZFN:SALE:AOP3:7LXQ:ZCM3:HXW6:EDUU:P6LQ:UUKR:XBRC:LQAR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

-
