### ISSUE TITLE
Permission Denied when starting container

### ISSUE THREAD

**Issue by donserdal** [bitnami/bitnami-docker-apache#95]
When running the docker container, I'm getting the following error: 

```
apache 20:51:09.46 Welcome to the Bitnami apache container
apache 20:51:09.46 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-apache
apache 20:51:09.47 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-apache/issues
apache 20:51:09.47 Send us your feedback at containers@bitnami.com
apache 20:51:09.47
apache 20:51:09.47 INFO  ==> ** Starting Apache setup **
apache 20:51:09.50 INFO  ==> Mounting application files from '/app'...
rm: cannot remove '/opt/bitnami/apache/htdocs/index.html': Permission denied
```

I'm using docker-compose to start the container:

```
version: '3'
services:
 apache:
  container_name: apache
  image: bitnami/apache:latest
  ports:
   - 80:8080
   - 443:8443
  volumes:
   - /home/user/Volumes/apache:/app
  restart: unless-stopped
```
The host is a Ubuntu 18.04 server and docker version is 5:19.03.2~3-0~ubuntu-bionic
It seems the problem is line 180 in the libapache.sh file. It seems to be a permission issue, what can I do to resolve it?
